# 网站地址
url: http://dawndiy.com

# 文件字符编码
encoding: UTF-8
# 时区
timezone: Asia/Shanghai
# 禁用 自定义插件
safe: false
# 为相关文章生成索引
lsi: false
highlighter: pygments
# 分页
paginate: 5
paginate_path: "page:num"

markdown: redcarpet
redcarpet:
    extenstions: [
        "fenced_code_blocks",
        "tables",
        "no_intra_emphasis",
        "autolink"
    ]

gems: [jekyll-paginate]
